spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChengBinH/config-server.git
          username: hcb739237663@gmail.com
          password: hcb739237663
          #下载在本地的路径
          basedir: ./config
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: antice.top
    username: guest
    password: guest
    port: 5672
eureka:
  client:
    service-url:
      # 注册多个服务中心,用,好隔开
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"

