#server:
#  port: 8080
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://antice.top:3306/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: googlemysql
  jpa:
    show-sql: true
  rabbitmq:
    host: antice.top
    username: google
    password: googlerabbitmq
    port: 5672
env:
  dev
