spring:
  datasource:
    url: jdbc:mysql://192.168.123.41/weather?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true

alibaba:
  city:
    host: https://jisutqybmf.market.alicloudapi.com
    city: /weather/city
    weather: /weather/query
    appSecret: b167080660982f053fd8dc07d89b090f
    appCode: 6a3aa81479f346fa848b4d48099ca886
    method: GET

server:
  servlet:
    context-path: /weather
